const philosophicalInquiries = [
  "Is success more about discipline or luck?",
  "Should happiness be the main goal of life?",
  "Is school designed for learning or obedience?",
  "Can money buy freedom more than happiness?",
  "Are most friendships based on convenience?",
  "Should people always tell the truth?",
  "Is suffering necessary for growth?",
  "Are smart people happier or more troubled?",
  "Is confidence built or born?",
  "Should society reward talent more than hard work?",
  "Is failure more valuable than success?",
  "Can loneliness be beneficial?",
  "Is social media helping or harming humanity?",
  "Should teenagers focus on fun or future-building?",
  "Is discipline stronger than motivation?",
  "Can love last without respect?",
  "Should people forgive betrayal?",
  "Is revenge ever justified?",
  "Are humans naturally selfish?",
  "Is peace better than ambition?",
  "Should parents be strict or understanding?",
  "Is emotional intelligence more important than IQ?",
  "Can people truly change?",
  "Should you judge people by actions or intentions?",
  "Is being feared more useful than being liked?",
  "Should governments limit freedom for safety?",
  "Is equality realistic or just idealistic?",
  "Does democracy always produce good outcomes?",
  "Should wealthy people have more influence?",
  "Is censorship ever acceptable?",
  "Is technology making people weaker mentally?",
  "Will AI improve humanity or damage it?",
  "Should coding be taught like Math in schools?",
  "Is privacy dying in modern society?",
  "Are phones reducing attention spans permanently?",
  "Should people trust algorithms with decisions?",
  "Is progress always good?",
  "Are humans becoming too dependent on convenience?",
  "Can machines ever replace wisdom?",
  "Should children have screen-time limits?",
  "Is hard work overrated?",
  "Should passion guide career choice?",
  "Is job security more important than meaning?",
  "Should people start businesses young?",
  "Is entrepreneurship glamorized too much?",
  "Are grades a fair measure of ability?",
  "Should schools teach money skills instead of some subjects?",
  "Is university losing value?",
  "Can someone be successful without credentials?",
  "Is specialization better than being multi-skilled?",
  "Should people chase status?",
  "Is reputation more valuable than money?",
  "Can honesty harm success?",
  "Should kindness have limits?",
  "Is manipulation ever acceptable?",
  "Are nice people often taken advantage of?",
  "Should loyalty come before truth?",
  "Is respect earned or given?",
  "Can power corrupt everyone?",
  "Is humility always a virtue?",
  "Is overthinking a sign of intelligence or weakness?",
  "Should emotions be controlled or expressed?",
  "Can anger be useful?",
  "Is insecurity necessary for self-improvement?",
  "Are mentally strong people made through hardship?",
  "Should people compare themselves to others?",
  "Is confidence possible without achievement?",
  "Can sadness improve wisdom?",
  "Is peace of mind worth more than ambition?",
  "Should people hide weakness?",
  "Is modern dating harder than past generations?",
  "Should love be practical or emotional?",
  "Can relationships survive without shared values?",
  "Is jealousy natural or toxic?",
  "Should people stay friends after betrayal?",
  "Is marriage still necessary?",
  "Should people prioritize self-love before relationships?",
  "Can attraction grow over time?",
  "Is commitment more important than passion?",
  "Are expectations ruining relationships?",
  "Is human nature fixed or flexible?",
  "Do people deserve second chances?",
  "Is morality objective or personal?",
  "Should laws reflect morality?",
  "Is freedom possible without responsibility?",
  "Are most people living unconsciously?",
  "Is purpose discovered or created?",
  "Does life need meaning to be worthwhile?",
  "Is death what gives life value?",
  "Should people pursue truth even if painful?",
  "Is competition necessary for excellence?",
  "Should society slow down and value simplicity?",
  "Are cities better than quiet living?",
  "Is fame more curse than blessing?",
  "Should everyone aim to lead?",
  "Is boredom necessary for creativity?",
  "Are routines liberating or limiting?",
  "Should people optimize life too much?",
  "Is inner peace the highest achievement?",
  "If you could master one trait, what should it be and why?"
];

const triggerButton = document.querySelector("#trigger-btn")
const displayInquiry = document.querySelector("#display-inquiry")

function generateOneInquiry() {
    return Math.floor(Math.random() * philosophicalInquiries.length)
}

triggerButton.addEventListener("click", () => {
    const inquiryIndex = generateOneInquiry()
    displayInquiry.style.display = "block"
    displayInquiry.textContent = philosophicalInquiries[inquiryIndex]
})